### ISSUE TITLE
UX Improvement: Social links on project modals

### ISSUE THREAD

**Issue by srijonsaha** [ubclaunchpad/new#95]
Right now on my 13" laptop with Chrome on fullscreen, the social icons are hidden from view. Unless I scroll (there's no indication that there's more content to scroll), I won't see the social buttons. I think the social buttons could be moved right below the title or short description. Or the video/image can be made smaller to fit everything in the modal without scrolling.
<img width="868" alt="Screen Shot 2020-04-25 at 1 58 24 PM" src="https://user-images.githubusercontent.com/33412649/80290879-74a46480-86fd-11ea-8e04-2a27c3462fc4.png">

**Comment by bobheadxi** [comment]
@srijonsaha how does it looks now? https://ubclaunchpad.github.io/new/

**Comment by srijonsaha** [comment]
I like it.

**Comment by bobheadxi** [comment]
Great! Marking this as done for now :)
